/* 
 * PassportPDF
 *
 * Copyright © 2018 ORPALIS - http://www.orpalis.com
 *
 * OpenAPI spec version: v1
 * Contact: contact@orpalis.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = PassportPDF.Client.SwaggerDateConverter;

namespace PassportPDF.Model
{
    /// <summary>
    /// Represents the parameters for a Save action.
    /// </summary>
    [DataContract]
    public partial class DocuViewareSaveParameters :  IEquatable<DocuViewareSaveParameters>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocuViewareSaveParameters" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DocuViewareSaveParameters() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DocuViewareSaveParameters" /> class.
        /// </summary>
        /// <param name="SessionId">Specifies the unique identifier used to identify the user session. (required).</param>
        /// <param name="ControlId">Specifies the identifier associated with the control. (required).</param>
        /// <param name="FileName">Specifies the name of the file to create. (required).</param>
        /// <param name="Format">Specifies the format of the document to save.  Supported values are tiff, pdf, pdf/a, pdf/a1a, pdf/a1b, pdf/a2a, pdf/a2b, pdf/a2u, pdf/a3a, pdf/a3b, pdf/a3u. (required).</param>
        /// <param name="PageRange">Specifies the number of the page, or the range of pages to be saved into the new file..</param>
        public DocuViewareSaveParameters(string SessionId = default(string), string ControlId = default(string), string FileName = default(string), string Format = default(string), string PageRange = default(string))
        {
            // to ensure "SessionId" is required (not null)
            if (SessionId == null)
            {
                throw new InvalidDataException("SessionId is a required property for DocuViewareSaveParameters and cannot be null");
            }
            else
            {
                this.SessionId = SessionId;
            }
            // to ensure "ControlId" is required (not null)
            if (ControlId == null)
            {
                throw new InvalidDataException("ControlId is a required property for DocuViewareSaveParameters and cannot be null");
            }
            else
            {
                this.ControlId = ControlId;
            }
            // to ensure "FileName" is required (not null)
            if (FileName == null)
            {
                throw new InvalidDataException("FileName is a required property for DocuViewareSaveParameters and cannot be null");
            }
            else
            {
                this.FileName = FileName;
            }
            // to ensure "Format" is required (not null)
            if (Format == null)
            {
                throw new InvalidDataException("Format is a required property for DocuViewareSaveParameters and cannot be null");
            }
            else
            {
                this.Format = Format;
            }
            this.PageRange = PageRange;
        }
        
        /// <summary>
        /// Specifies the unique identifier used to identify the user session.
        /// </summary>
        /// <value>Specifies the unique identifier used to identify the user session.</value>
        [DataMember(Name="sessionId", EmitDefaultValue=false)]
        public string SessionId { get; set; }

        /// <summary>
        /// Specifies the identifier associated with the control.
        /// </summary>
        /// <value>Specifies the identifier associated with the control.</value>
        [DataMember(Name="controlId", EmitDefaultValue=false)]
        public string ControlId { get; set; }

        /// <summary>
        /// Specifies the name of the file to create.
        /// </summary>
        /// <value>Specifies the name of the file to create.</value>
        [DataMember(Name="fileName", EmitDefaultValue=false)]
        public string FileName { get; set; }

        /// <summary>
        /// Specifies the format of the document to save.  Supported values are tiff, pdf, pdf/a, pdf/a1a, pdf/a1b, pdf/a2a, pdf/a2b, pdf/a2u, pdf/a3a, pdf/a3b, pdf/a3u.
        /// </summary>
        /// <value>Specifies the format of the document to save.  Supported values are tiff, pdf, pdf/a, pdf/a1a, pdf/a1b, pdf/a2a, pdf/a2b, pdf/a2u, pdf/a3a, pdf/a3b, pdf/a3u.</value>
        [DataMember(Name="format", EmitDefaultValue=false)]
        public string Format { get; set; }

        /// <summary>
        /// Specifies the number of the page, or the range of pages to be saved into the new file.
        /// </summary>
        /// <value>Specifies the number of the page, or the range of pages to be saved into the new file.</value>
        [DataMember(Name="pageRange", EmitDefaultValue=false)]
        public string PageRange { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DocuViewareSaveParameters {\n");
            sb.Append("  SessionId: ").Append(SessionId).Append("\n");
            sb.Append("  ControlId: ").Append(ControlId).Append("\n");
            sb.Append("  FileName: ").Append(FileName).Append("\n");
            sb.Append("  Format: ").Append(Format).Append("\n");
            sb.Append("  PageRange: ").Append(PageRange).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DocuViewareSaveParameters);
        }

        /// <summary>
        /// Returns true if DocuViewareSaveParameters instances are equal
        /// </summary>
        /// <param name="input">Instance of DocuViewareSaveParameters to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DocuViewareSaveParameters input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SessionId == input.SessionId ||
                    (this.SessionId != null &&
                    this.SessionId.Equals(input.SessionId))
                ) && 
                (
                    this.ControlId == input.ControlId ||
                    (this.ControlId != null &&
                    this.ControlId.Equals(input.ControlId))
                ) && 
                (
                    this.FileName == input.FileName ||
                    (this.FileName != null &&
                    this.FileName.Equals(input.FileName))
                ) && 
                (
                    this.Format == input.Format ||
                    (this.Format != null &&
                    this.Format.Equals(input.Format))
                ) && 
                (
                    this.PageRange == input.PageRange ||
                    (this.PageRange != null &&
                    this.PageRange.Equals(input.PageRange))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SessionId != null)
                    hashCode = hashCode * 59 + this.SessionId.GetHashCode();
                if (this.ControlId != null)
                    hashCode = hashCode * 59 + this.ControlId.GetHashCode();
                if (this.FileName != null)
                    hashCode = hashCode * 59 + this.FileName.GetHashCode();
                if (this.Format != null)
                    hashCode = hashCode * 59 + this.Format.GetHashCode();
                if (this.PageRange != null)
                    hashCode = hashCode * 59 + this.PageRange.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
