/* 
 * PassportPDF
 *
 * Copyright © 2018 ORPALIS - http://www.orpalis.com
 *
 * OpenAPI spec version: v1
 * Contact: contact@orpalis.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = PassportPDF.Client.SwaggerDateConverter;

namespace PassportPDF.Model
{
    /// <summary>
    /// Represents information about the layout of a content, on the page it is drawn onto.
    /// </summary>
    [DataContract]
    public partial class DrawableContentLayoutParameters :  IEquatable<DrawableContentLayoutParameters>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets HorizontalPosition
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum HorizontalPositionEnum
        {
            
            /// <summary>
            /// Enum Center for "Center"
            /// </summary>
            [EnumMember(Value = "Center")]
            Center = 1,
            
            /// <summary>
            /// Enum Left for "Left"
            /// </summary>
            [EnumMember(Value = "Left")]
            Left = 2,
            
            /// <summary>
            /// Enum Right for "Right"
            /// </summary>
            [EnumMember(Value = "Right")]
            Right = 3,
            
            /// <summary>
            /// Enum Absolute for "Absolute"
            /// </summary>
            [EnumMember(Value = "Absolute")]
            Absolute = 4
        }

        /// <summary>
        /// Gets or Sets HorizontalPosition
        /// </summary>
        [DataMember(Name="horizontalPosition", EmitDefaultValue=false)]
        public HorizontalPositionEnum? HorizontalPosition { get; set; }
        /// <summary>
        /// Gets or Sets VerticalPosition
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum VerticalPositionEnum
        {
            
            /// <summary>
            /// Enum Center for "Center"
            /// </summary>
            [EnumMember(Value = "Center")]
            Center = 1,
            
            /// <summary>
            /// Enum Top for "Top"
            /// </summary>
            [EnumMember(Value = "Top")]
            Top = 2,
            
            /// <summary>
            /// Enum Bottom for "Bottom"
            /// </summary>
            [EnumMember(Value = "Bottom")]
            Bottom = 3,
            
            /// <summary>
            /// Enum Absolute for "Absolute"
            /// </summary>
            [EnumMember(Value = "Absolute")]
            Absolute = 4
        }

        /// <summary>
        /// Gets or Sets VerticalPosition
        /// </summary>
        [DataMember(Name="verticalPosition", EmitDefaultValue=false)]
        public VerticalPositionEnum? VerticalPosition { get; set; }
        /// <summary>
        /// Gets or Sets Size
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum SizeEnum
        {
            
            /// <summary>
            /// Enum Small for "Small"
            /// </summary>
            [EnumMember(Value = "Small")]
            Small = 1,
            
            /// <summary>
            /// Enum Medium for "Medium"
            /// </summary>
            [EnumMember(Value = "Medium")]
            Medium = 2,
            
            /// <summary>
            /// Enum Large for "Large"
            /// </summary>
            [EnumMember(Value = "Large")]
            Large = 3,
            
            /// <summary>
            /// Enum Absolute for "Absolute"
            /// </summary>
            [EnumMember(Value = "Absolute")]
            Absolute = 4,
            
            /// <summary>
            /// Enum AutoFit for "AutoFit"
            /// </summary>
            [EnumMember(Value = "AutoFit")]
            AutoFit = 5
        }

        /// <summary>
        /// Gets or Sets Size
        /// </summary>
        [DataMember(Name="size", EmitDefaultValue=false)]
        public SizeEnum? Size { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DrawableContentLayoutParameters" /> class.
        /// </summary>
        /// <param name="HorizontalPosition">HorizontalPosition.</param>
        /// <param name="VerticalPosition">VerticalPosition.</param>
        /// <param name="Size">Size.</param>
        /// <param name="IndentFromEdges">IndentFromEdges.</param>
        /// <param name="AbsolutePositionX">AbsolutePositionX.</param>
        /// <param name="AbsolutePositionY">AbsolutePositionY.</param>
        /// <param name="AbsoluteWidth">AbsoluteWidth.</param>
        /// <param name="AbsoluteHeight">AbsoluteHeight.</param>
        public DrawableContentLayoutParameters(HorizontalPositionEnum? HorizontalPosition = default(HorizontalPositionEnum?), VerticalPositionEnum? VerticalPosition = default(VerticalPositionEnum?), SizeEnum? Size = default(SizeEnum?), bool? IndentFromEdges = default(bool?), float? AbsolutePositionX = default(float?), float? AbsolutePositionY = default(float?), float? AbsoluteWidth = default(float?), float? AbsoluteHeight = default(float?))
        {
            this.HorizontalPosition = HorizontalPosition;
            this.VerticalPosition = VerticalPosition;
            this.Size = Size;
            this.IndentFromEdges = IndentFromEdges;
            this.AbsolutePositionX = AbsolutePositionX;
            this.AbsolutePositionY = AbsolutePositionY;
            this.AbsoluteWidth = AbsoluteWidth;
            this.AbsoluteHeight = AbsoluteHeight;
        }
        



        /// <summary>
        /// Gets or Sets IndentFromEdges
        /// </summary>
        [DataMember(Name="indentFromEdges", EmitDefaultValue=false)]
        public bool? IndentFromEdges { get; set; }

        /// <summary>
        /// Gets or Sets AbsolutePositionX
        /// </summary>
        [DataMember(Name="absolutePositionX", EmitDefaultValue=false)]
        public float? AbsolutePositionX { get; set; }

        /// <summary>
        /// Gets or Sets AbsolutePositionY
        /// </summary>
        [DataMember(Name="absolutePositionY", EmitDefaultValue=false)]
        public float? AbsolutePositionY { get; set; }

        /// <summary>
        /// Gets or Sets AbsoluteWidth
        /// </summary>
        [DataMember(Name="absoluteWidth", EmitDefaultValue=false)]
        public float? AbsoluteWidth { get; set; }

        /// <summary>
        /// Gets or Sets AbsoluteHeight
        /// </summary>
        [DataMember(Name="absoluteHeight", EmitDefaultValue=false)]
        public float? AbsoluteHeight { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DrawableContentLayoutParameters {\n");
            sb.Append("  HorizontalPosition: ").Append(HorizontalPosition).Append("\n");
            sb.Append("  VerticalPosition: ").Append(VerticalPosition).Append("\n");
            sb.Append("  Size: ").Append(Size).Append("\n");
            sb.Append("  IndentFromEdges: ").Append(IndentFromEdges).Append("\n");
            sb.Append("  AbsolutePositionX: ").Append(AbsolutePositionX).Append("\n");
            sb.Append("  AbsolutePositionY: ").Append(AbsolutePositionY).Append("\n");
            sb.Append("  AbsoluteWidth: ").Append(AbsoluteWidth).Append("\n");
            sb.Append("  AbsoluteHeight: ").Append(AbsoluteHeight).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DrawableContentLayoutParameters);
        }

        /// <summary>
        /// Returns true if DrawableContentLayoutParameters instances are equal
        /// </summary>
        /// <param name="input">Instance of DrawableContentLayoutParameters to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DrawableContentLayoutParameters input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.HorizontalPosition == input.HorizontalPosition ||
                    (this.HorizontalPosition != null &&
                    this.HorizontalPosition.Equals(input.HorizontalPosition))
                ) && 
                (
                    this.VerticalPosition == input.VerticalPosition ||
                    (this.VerticalPosition != null &&
                    this.VerticalPosition.Equals(input.VerticalPosition))
                ) && 
                (
                    this.Size == input.Size ||
                    (this.Size != null &&
                    this.Size.Equals(input.Size))
                ) && 
                (
                    this.IndentFromEdges == input.IndentFromEdges ||
                    (this.IndentFromEdges != null &&
                    this.IndentFromEdges.Equals(input.IndentFromEdges))
                ) && 
                (
                    this.AbsolutePositionX == input.AbsolutePositionX ||
                    (this.AbsolutePositionX != null &&
                    this.AbsolutePositionX.Equals(input.AbsolutePositionX))
                ) && 
                (
                    this.AbsolutePositionY == input.AbsolutePositionY ||
                    (this.AbsolutePositionY != null &&
                    this.AbsolutePositionY.Equals(input.AbsolutePositionY))
                ) && 
                (
                    this.AbsoluteWidth == input.AbsoluteWidth ||
                    (this.AbsoluteWidth != null &&
                    this.AbsoluteWidth.Equals(input.AbsoluteWidth))
                ) && 
                (
                    this.AbsoluteHeight == input.AbsoluteHeight ||
                    (this.AbsoluteHeight != null &&
                    this.AbsoluteHeight.Equals(input.AbsoluteHeight))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.HorizontalPosition != null)
                    hashCode = hashCode * 59 + this.HorizontalPosition.GetHashCode();
                if (this.VerticalPosition != null)
                    hashCode = hashCode * 59 + this.VerticalPosition.GetHashCode();
                if (this.Size != null)
                    hashCode = hashCode * 59 + this.Size.GetHashCode();
                if (this.IndentFromEdges != null)
                    hashCode = hashCode * 59 + this.IndentFromEdges.GetHashCode();
                if (this.AbsolutePositionX != null)
                    hashCode = hashCode * 59 + this.AbsolutePositionX.GetHashCode();
                if (this.AbsolutePositionY != null)
                    hashCode = hashCode * 59 + this.AbsolutePositionY.GetHashCode();
                if (this.AbsoluteWidth != null)
                    hashCode = hashCode * 59 + this.AbsoluteWidth.GetHashCode();
                if (this.AbsoluteHeight != null)
                    hashCode = hashCode * 59 + this.AbsoluteHeight.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
