/* 
 * PassportPDF
 *
 * Copyright © 2018 ORPALIS - http://www.orpalis.com
 *
 * OpenAPI spec version: v1
 * Contact: contact@orpalis.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = PassportPDF.Client.SwaggerDateConverter;

namespace PassportPDF.Model
{
    /// <summary>
    /// Represents the parameters for an image loading request.
    /// </summary>
    [DataContract]
    public partial class LoadImageFromByteArrayParameters :  IEquatable<LoadImageFromByteArrayParameters>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets ContentEncoding
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ContentEncodingEnum
        {
            
            /// <summary>
            /// Enum Identity for "Identity"
            /// </summary>
            [EnumMember(Value = "Identity")]
            Identity = 1,
            
            /// <summary>
            /// Enum Gzip for "Gzip"
            /// </summary>
            [EnumMember(Value = "Gzip")]
            Gzip = 2
        }

        /// <summary>
        /// Gets or Sets ContentEncoding
        /// </summary>
        [DataMember(Name="contentEncoding", EmitDefaultValue=false)]
        public ContentEncodingEnum? ContentEncoding { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="LoadImageFromByteArrayParameters" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LoadImageFromByteArrayParameters() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LoadImageFromByteArrayParameters" /> class.
        /// </summary>
        /// <param name="Content">Content (required).</param>
        /// <param name="FileName">FileName.</param>
        /// <param name="ContentEncoding">ContentEncoding (default to ContentEncodingEnum.Identity).</param>
        public LoadImageFromByteArrayParameters(byte[] Content = default(byte[]), string FileName = default(string), ContentEncodingEnum? ContentEncoding = ContentEncodingEnum.Identity)
        {
            // to ensure "Content" is required (not null)
            if (Content == null)
            {
                throw new InvalidDataException("Content is a required property for LoadImageFromByteArrayParameters and cannot be null");
            }
            else
            {
                this.Content = Content;
            }
            this.FileName = FileName;
            // use default value if no "ContentEncoding" provided
            if (ContentEncoding == null)
            {
                this.ContentEncoding = ContentEncodingEnum.Identity;
            }
            else
            {
                this.ContentEncoding = ContentEncoding;
            }
        }
        
        /// <summary>
        /// Gets or Sets Content
        /// </summary>
        [DataMember(Name="content", EmitDefaultValue=false)]
        public byte[] Content { get; set; }

        /// <summary>
        /// Gets or Sets FileName
        /// </summary>
        [DataMember(Name="fileName", EmitDefaultValue=false)]
        public string FileName { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LoadImageFromByteArrayParameters {\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("  FileName: ").Append(FileName).Append("\n");
            sb.Append("  ContentEncoding: ").Append(ContentEncoding).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LoadImageFromByteArrayParameters);
        }

        /// <summary>
        /// Returns true if LoadImageFromByteArrayParameters instances are equal
        /// </summary>
        /// <param name="input">Instance of LoadImageFromByteArrayParameters to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LoadImageFromByteArrayParameters input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Content == input.Content ||
                    (this.Content != null &&
                    this.Content.Equals(input.Content))
                ) && 
                (
                    this.FileName == input.FileName ||
                    (this.FileName != null &&
                    this.FileName.Equals(input.FileName))
                ) && 
                (
                    this.ContentEncoding == input.ContentEncoding ||
                    (this.ContentEncoding != null &&
                    this.ContentEncoding.Equals(input.ContentEncoding))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Content != null)
                    hashCode = hashCode * 59 + this.Content.GetHashCode();
                if (this.FileName != null)
                    hashCode = hashCode * 59 + this.FileName.GetHashCode();
                if (this.ContentEncoding != null)
                    hashCode = hashCode * 59 + this.ContentEncoding.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
