/* 
 * PassportPDF
 *
 * Copyright © 2018 ORPALIS - http://www.orpalis.com
 *
 * OpenAPI spec version: v1
 * Contact: contact@orpalis.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = PassportPDF.Client.SwaggerDateConverter;

namespace PassportPDF.Model
{
    /// <summary>
    /// Represents the parameters for text content.
    /// </summary>
    [DataContract]
    public partial class PdfAlignedTextParameters :  IEquatable<PdfAlignedTextParameters>, IValidatableObject
    {
        /// <summary>
        /// Specifies the name of the standard font to be used.
        /// </summary>
        /// <value>Specifies the name of the standard font to be used.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StandardFontNameEnum
        {
            
            /// <summary>
            /// Enum Courier for "Courier"
            /// </summary>
            [EnumMember(Value = "Courier")]
            Courier = 1,
            
            /// <summary>
            /// Enum Helvetica for "Helvetica"
            /// </summary>
            [EnumMember(Value = "Helvetica")]
            Helvetica = 2,
            
            /// <summary>
            /// Enum Times for "Times"
            /// </summary>
            [EnumMember(Value = "Times")]
            Times = 3,
            
            /// <summary>
            /// Enum Symbol for "Symbol"
            /// </summary>
            [EnumMember(Value = "Symbol")]
            Symbol = 4,
            
            /// <summary>
            /// Enum ZapfDingbats for "ZapfDingbats"
            /// </summary>
            [EnumMember(Value = "ZapfDingbats")]
            ZapfDingbats = 5
        }

        /// <summary>
        /// Specifies the name of the standard font to be used.
        /// </summary>
        /// <value>Specifies the name of the standard font to be used.</value>
        [DataMember(Name="standardFontName", EmitDefaultValue=false)]
        public StandardFontNameEnum? StandardFontName { get; set; }
        /// <summary>
        /// Specifies the style of the font.
        /// </summary>
        /// <value>Specifies the style of the font.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum FontStyleEnum
        {
            
            /// <summary>
            /// Enum Regular for "Regular"
            /// </summary>
            [EnumMember(Value = "Regular")]
            Regular = 1,
            
            /// <summary>
            /// Enum Bold for "Bold"
            /// </summary>
            [EnumMember(Value = "Bold")]
            Bold = 2,
            
            /// <summary>
            /// Enum Italic for "Italic"
            /// </summary>
            [EnumMember(Value = "Italic")]
            Italic = 3,
            
            /// <summary>
            /// Enum BoldItalic for "BoldItalic"
            /// </summary>
            [EnumMember(Value = "BoldItalic")]
            BoldItalic = 4
        }

        /// <summary>
        /// Specifies the style of the font.
        /// </summary>
        /// <value>Specifies the style of the font.</value>
        [DataMember(Name="fontStyle", EmitDefaultValue=false)]
        public FontStyleEnum? FontStyle { get; set; }
        /// <summary>
        /// Specifies the vertical alignment of the text.
        /// </summary>
        /// <value>Specifies the vertical alignment of the text.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TextVerticalAlignmentEnum
        {
            
            /// <summary>
            /// Enum Near for "Near"
            /// </summary>
            [EnumMember(Value = "Near")]
            Near = 1,
            
            /// <summary>
            /// Enum Center for "Center"
            /// </summary>
            [EnumMember(Value = "Center")]
            Center = 2,
            
            /// <summary>
            /// Enum Far for "Far"
            /// </summary>
            [EnumMember(Value = "Far")]
            Far = 3
        }

        /// <summary>
        /// Specifies the vertical alignment of the text.
        /// </summary>
        /// <value>Specifies the vertical alignment of the text.</value>
        [DataMember(Name="textVerticalAlignment", EmitDefaultValue=false)]
        public TextVerticalAlignmentEnum? TextVerticalAlignment { get; set; }
        /// <summary>
        /// Specifies the horizontal alignment of the text.
        /// </summary>
        /// <value>Specifies the horizontal alignment of the text.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TextHorizontalAlignmentEnum
        {
            
            /// <summary>
            /// Enum Near for "Near"
            /// </summary>
            [EnumMember(Value = "Near")]
            Near = 1,
            
            /// <summary>
            /// Enum Center for "Center"
            /// </summary>
            [EnumMember(Value = "Center")]
            Center = 2,
            
            /// <summary>
            /// Enum Far for "Far"
            /// </summary>
            [EnumMember(Value = "Far")]
            Far = 3
        }

        /// <summary>
        /// Specifies the horizontal alignment of the text.
        /// </summary>
        /// <value>Specifies the horizontal alignment of the text.</value>
        [DataMember(Name="textHorizontalAlignment", EmitDefaultValue=false)]
        public TextHorizontalAlignmentEnum? TextHorizontalAlignment { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PdfAlignedTextParameters" /> class.
        /// </summary>
        /// <param name="Text">Specifies the text..</param>
        /// <param name="TextColor">Specifies the color of the text, using the color name (ie: \&quot;red\&quot;) or its RGBa code (ie: \&quot;rgba(255,0,0,1)\&quot;)..</param>
        /// <param name="FontName">Specifies the name of the font to be used..</param>
        /// <param name="StandardFontName">Specifies the name of the standard font to be used..</param>
        /// <param name="FontStyle">Specifies the style of the font..</param>
        /// <param name="FontSize">Specifies the size of the font..</param>
        /// <param name="TextVerticalAlignment">Specifies the vertical alignment of the text..</param>
        /// <param name="TextHorizontalAlignment">Specifies the horizontal alignment of the text..</param>
        public PdfAlignedTextParameters(string Text = default(string), string TextColor = default(string), string FontName = default(string), StandardFontNameEnum? StandardFontName = default(StandardFontNameEnum?), FontStyleEnum? FontStyle = default(FontStyleEnum?), int? FontSize = default(int?), TextVerticalAlignmentEnum? TextVerticalAlignment = default(TextVerticalAlignmentEnum?), TextHorizontalAlignmentEnum? TextHorizontalAlignment = default(TextHorizontalAlignmentEnum?))
        {
            this.Text = Text;
            this.TextColor = TextColor;
            this.FontName = FontName;
            this.StandardFontName = StandardFontName;
            this.FontStyle = FontStyle;
            this.FontSize = FontSize;
            this.TextVerticalAlignment = TextVerticalAlignment;
            this.TextHorizontalAlignment = TextHorizontalAlignment;
        }
        
        /// <summary>
        /// Specifies the text.
        /// </summary>
        /// <value>Specifies the text.</value>
        [DataMember(Name="text", EmitDefaultValue=false)]
        public string Text { get; set; }

        /// <summary>
        /// Specifies the color of the text, using the color name (ie: \&quot;red\&quot;) or its RGBa code (ie: \&quot;rgba(255,0,0,1)\&quot;).
        /// </summary>
        /// <value>Specifies the color of the text, using the color name (ie: \&quot;red\&quot;) or its RGBa code (ie: \&quot;rgba(255,0,0,1)\&quot;).</value>
        [DataMember(Name="textColor", EmitDefaultValue=false)]
        public string TextColor { get; set; }

        /// <summary>
        /// Specifies the name of the font to be used.
        /// </summary>
        /// <value>Specifies the name of the font to be used.</value>
        [DataMember(Name="fontName", EmitDefaultValue=false)]
        public string FontName { get; set; }



        /// <summary>
        /// Specifies the size of the font.
        /// </summary>
        /// <value>Specifies the size of the font.</value>
        [DataMember(Name="fontSize", EmitDefaultValue=false)]
        public int? FontSize { get; set; }



        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PdfAlignedTextParameters {\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  TextColor: ").Append(TextColor).Append("\n");
            sb.Append("  FontName: ").Append(FontName).Append("\n");
            sb.Append("  StandardFontName: ").Append(StandardFontName).Append("\n");
            sb.Append("  FontStyle: ").Append(FontStyle).Append("\n");
            sb.Append("  FontSize: ").Append(FontSize).Append("\n");
            sb.Append("  TextVerticalAlignment: ").Append(TextVerticalAlignment).Append("\n");
            sb.Append("  TextHorizontalAlignment: ").Append(TextHorizontalAlignment).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PdfAlignedTextParameters);
        }

        /// <summary>
        /// Returns true if PdfAlignedTextParameters instances are equal
        /// </summary>
        /// <param name="input">Instance of PdfAlignedTextParameters to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PdfAlignedTextParameters input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Text == input.Text ||
                    (this.Text != null &&
                    this.Text.Equals(input.Text))
                ) && 
                (
                    this.TextColor == input.TextColor ||
                    (this.TextColor != null &&
                    this.TextColor.Equals(input.TextColor))
                ) && 
                (
                    this.FontName == input.FontName ||
                    (this.FontName != null &&
                    this.FontName.Equals(input.FontName))
                ) && 
                (
                    this.StandardFontName == input.StandardFontName ||
                    (this.StandardFontName != null &&
                    this.StandardFontName.Equals(input.StandardFontName))
                ) && 
                (
                    this.FontStyle == input.FontStyle ||
                    (this.FontStyle != null &&
                    this.FontStyle.Equals(input.FontStyle))
                ) && 
                (
                    this.FontSize == input.FontSize ||
                    (this.FontSize != null &&
                    this.FontSize.Equals(input.FontSize))
                ) && 
                (
                    this.TextVerticalAlignment == input.TextVerticalAlignment ||
                    (this.TextVerticalAlignment != null &&
                    this.TextVerticalAlignment.Equals(input.TextVerticalAlignment))
                ) && 
                (
                    this.TextHorizontalAlignment == input.TextHorizontalAlignment ||
                    (this.TextHorizontalAlignment != null &&
                    this.TextHorizontalAlignment.Equals(input.TextHorizontalAlignment))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Text != null)
                    hashCode = hashCode * 59 + this.Text.GetHashCode();
                if (this.TextColor != null)
                    hashCode = hashCode * 59 + this.TextColor.GetHashCode();
                if (this.FontName != null)
                    hashCode = hashCode * 59 + this.FontName.GetHashCode();
                if (this.StandardFontName != null)
                    hashCode = hashCode * 59 + this.StandardFontName.GetHashCode();
                if (this.FontStyle != null)
                    hashCode = hashCode * 59 + this.FontStyle.GetHashCode();
                if (this.FontSize != null)
                    hashCode = hashCode * 59 + this.FontSize.GetHashCode();
                if (this.TextVerticalAlignment != null)
                    hashCode = hashCode * 59 + this.TextVerticalAlignment.GetHashCode();
                if (this.TextHorizontalAlignment != null)
                    hashCode = hashCode * 59 + this.TextHorizontalAlignment.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
