/* 
 * PassportPDF
 *
 * Copyright © 2018 ORPALIS - http://www.orpalis.com
 *
 * OpenAPI spec version: v1
 * Contact: contact@orpalis.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = PassportPDF.Client.SwaggerDateConverter;

namespace PassportPDF.Model
{
    /// <summary>
    /// Represents the parameters for a digital signature action.
    /// </summary>
    [DataContract]
    public partial class PDFDigiSignParameters :  IEquatable<PDFDigiSignParameters>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets SignatureMode
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum SignatureModeEnum
        {
            
            /// <summary>
            /// Enum AdobePPKMS for "AdobePPKMS"
            /// </summary>
            [EnumMember(Value = "AdobePPKMS")]
            AdobePPKMS = 1,
            
            /// <summary>
            /// Enum AdobePPKLite for "AdobePPKLite"
            /// </summary>
            [EnumMember(Value = "AdobePPKLite")]
            AdobePPKLite = 2,
            
            /// <summary>
            /// Enum AdobeCADES for "AdobeCADES"
            /// </summary>
            [EnumMember(Value = "AdobeCADES")]
            AdobeCADES = 3
        }

        /// <summary>
        /// Gets or Sets SignatureMode
        /// </summary>
        [DataMember(Name="signatureMode", EmitDefaultValue=false)]
        public SignatureModeEnum? SignatureMode { get; set; }
        /// <summary>
        /// Gets or Sets SignatureCertificationLevel
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum SignatureCertificationLevelEnum
        {
            
            /// <summary>
            /// Enum NotCertified for "NotCertified"
            /// </summary>
            [EnumMember(Value = "NotCertified")]
            NotCertified = 1,
            
            /// <summary>
            /// Enum NoChanges for "NoChanges"
            /// </summary>
            [EnumMember(Value = "NoChanges")]
            NoChanges = 2,
            
            /// <summary>
            /// Enum FormFilling for "FormFilling"
            /// </summary>
            [EnumMember(Value = "FormFilling")]
            FormFilling = 3,
            
            /// <summary>
            /// Enum FormFillingAndAnnotations for "FormFillingAndAnnotations"
            /// </summary>
            [EnumMember(Value = "FormFillingAndAnnotations")]
            FormFillingAndAnnotations = 4
        }

        /// <summary>
        /// Gets or Sets SignatureCertificationLevel
        /// </summary>
        [DataMember(Name="signatureCertificationLevel", EmitDefaultValue=false)]
        public SignatureCertificationLevelEnum? SignatureCertificationLevel { get; set; }
        /// <summary>
        /// Gets or Sets SignatureHashAlgorithm
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum SignatureHashAlgorithmEnum
        {
            
            /// <summary>
            /// Enum SHA1 for "SHA1"
            /// </summary>
            [EnumMember(Value = "SHA1")]
            SHA1 = 1,
            
            /// <summary>
            /// Enum SHA256 for "SHA256"
            /// </summary>
            [EnumMember(Value = "SHA256")]
            SHA256 = 2,
            
            /// <summary>
            /// Enum SHA512 for "SHA512"
            /// </summary>
            [EnumMember(Value = "SHA512")]
            SHA512 = 3,
            
            /// <summary>
            /// Enum SHA224 for "SHA224"
            /// </summary>
            [EnumMember(Value = "SHA224")]
            SHA224 = 4,
            
            /// <summary>
            /// Enum SHA384 for "SHA384"
            /// </summary>
            [EnumMember(Value = "SHA384")]
            SHA384 = 5
        }

        /// <summary>
        /// Gets or Sets SignatureHashAlgorithm
        /// </summary>
        [DataMember(Name="signatureHashAlgorithm", EmitDefaultValue=false)]
        public SignatureHashAlgorithmEnum? SignatureHashAlgorithm { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PDFDigiSignParameters" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PDFDigiSignParameters() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PDFDigiSignParameters" /> class.
        /// </summary>
        /// <param name="CertificateData">CertificateData (required).</param>
        /// <param name="CertificatePassword">CertificatePassword (required).</param>
        /// <param name="FileId">FileId (required).</param>
        /// <param name="SignatureMode">SignatureMode (default to SignatureModeEnum.AdobePPKMS).</param>
        /// <param name="SignatureCertificationLevel">SignatureCertificationLevel (default to SignatureCertificationLevelEnum.NotCertified).</param>
        /// <param name="SignatureHashAlgorithm">SignatureHashAlgorithm (default to SignatureHashAlgorithmEnum.SHA256).</param>
        /// <param name="SignerName">SignerName (default to &quot;PassportPDF&quot;).</param>
        /// <param name="Reason">Reason.</param>
        /// <param name="Location">Location.</param>
        /// <param name="ContactInfo">ContactInfo.</param>
        /// <param name="TimeStampURL">TimeStampURL.</param>
        /// <param name="TimeStampUserName">TimeStampUserName.</param>
        /// <param name="TimeStampPassword">TimeStampPassword.</param>
        /// <param name="Linearize">Linearize.</param>
        /// <param name="DrawSignature">DrawSignature.</param>
        /// <param name="PageNumber">PageNumber (default to 1).</param>
        /// <param name="ShowValidationMark">ShowValidationMark.</param>
        /// <param name="ImageData">ImageData.</param>
        /// <param name="SignatureLayout">SignatureLayout.</param>
        /// <param name="SignatureText">SignatureText.</param>
        public PDFDigiSignParameters(byte[] CertificateData = default(byte[]), string CertificatePassword = default(string), string FileId = default(string), SignatureModeEnum? SignatureMode = SignatureModeEnum.AdobePPKMS, SignatureCertificationLevelEnum? SignatureCertificationLevel = SignatureCertificationLevelEnum.NotCertified, SignatureHashAlgorithmEnum? SignatureHashAlgorithm = SignatureHashAlgorithmEnum.SHA256, string SignerName = "PassportPDF", string Reason = default(string), string Location = default(string), string ContactInfo = default(string), string TimeStampURL = default(string), string TimeStampUserName = default(string), string TimeStampPassword = default(string), bool? Linearize = default(bool?), bool? DrawSignature = default(bool?), int? PageNumber = 1, bool? ShowValidationMark = default(bool?), byte[] ImageData = default(byte[]), DrawableContentLayoutParameters SignatureLayout = default(DrawableContentLayoutParameters), PdfStandardFontAlignedTextParameters SignatureText = default(PdfStandardFontAlignedTextParameters))
        {
            // to ensure "CertificateData" is required (not null)
            if (CertificateData == null)
            {
                throw new InvalidDataException("CertificateData is a required property for PDFDigiSignParameters and cannot be null");
            }
            else
            {
                this.CertificateData = CertificateData;
            }
            // to ensure "CertificatePassword" is required (not null)
            if (CertificatePassword == null)
            {
                throw new InvalidDataException("CertificatePassword is a required property for PDFDigiSignParameters and cannot be null");
            }
            else
            {
                this.CertificatePassword = CertificatePassword;
            }
            // to ensure "FileId" is required (not null)
            if (FileId == null)
            {
                throw new InvalidDataException("FileId is a required property for PDFDigiSignParameters and cannot be null");
            }
            else
            {
                this.FileId = FileId;
            }
            // use default value if no "SignatureMode" provided
            if (SignatureMode == null)
            {
                this.SignatureMode = SignatureModeEnum.AdobePPKMS;
            }
            else
            {
                this.SignatureMode = SignatureMode;
            }
            // use default value if no "SignatureCertificationLevel" provided
            if (SignatureCertificationLevel == null)
            {
                this.SignatureCertificationLevel = SignatureCertificationLevelEnum.NotCertified;
            }
            else
            {
                this.SignatureCertificationLevel = SignatureCertificationLevel;
            }
            // use default value if no "SignatureHashAlgorithm" provided
            if (SignatureHashAlgorithm == null)
            {
                this.SignatureHashAlgorithm = SignatureHashAlgorithmEnum.SHA256;
            }
            else
            {
                this.SignatureHashAlgorithm = SignatureHashAlgorithm;
            }
            // use default value if no "SignerName" provided
            if (SignerName == null)
            {
                this.SignerName = "PassportPDF";
            }
            else
            {
                this.SignerName = SignerName;
            }
            this.Reason = Reason;
            this.Location = Location;
            this.ContactInfo = ContactInfo;
            this.TimeStampURL = TimeStampURL;
            this.TimeStampUserName = TimeStampUserName;
            this.TimeStampPassword = TimeStampPassword;
            this.Linearize = Linearize;
            this.DrawSignature = DrawSignature;
            // use default value if no "PageNumber" provided
            if (PageNumber == null)
            {
                this.PageNumber = 1;
            }
            else
            {
                this.PageNumber = PageNumber;
            }
            this.ShowValidationMark = ShowValidationMark;
            this.ImageData = ImageData;
            this.SignatureLayout = SignatureLayout;
            this.SignatureText = SignatureText;
        }
        
        /// <summary>
        /// Gets or Sets CertificateData
        /// </summary>
        [DataMember(Name="certificateData", EmitDefaultValue=false)]
        public byte[] CertificateData { get; set; }

        /// <summary>
        /// Gets or Sets CertificatePassword
        /// </summary>
        [DataMember(Name="certificatePassword", EmitDefaultValue=false)]
        public string CertificatePassword { get; set; }

        /// <summary>
        /// Gets or Sets FileId
        /// </summary>
        [DataMember(Name="fileId", EmitDefaultValue=false)]
        public string FileId { get; set; }




        /// <summary>
        /// Gets or Sets SignerName
        /// </summary>
        [DataMember(Name="signerName", EmitDefaultValue=false)]
        public string SignerName { get; set; }

        /// <summary>
        /// Gets or Sets Reason
        /// </summary>
        [DataMember(Name="reason", EmitDefaultValue=false)]
        public string Reason { get; set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [DataMember(Name="location", EmitDefaultValue=false)]
        public string Location { get; set; }

        /// <summary>
        /// Gets or Sets ContactInfo
        /// </summary>
        [DataMember(Name="contactInfo", EmitDefaultValue=false)]
        public string ContactInfo { get; set; }

        /// <summary>
        /// Gets or Sets TimeStampURL
        /// </summary>
        [DataMember(Name="timeStampURL", EmitDefaultValue=false)]
        public string TimeStampURL { get; set; }

        /// <summary>
        /// Gets or Sets TimeStampUserName
        /// </summary>
        [DataMember(Name="timeStampUserName", EmitDefaultValue=false)]
        public string TimeStampUserName { get; set; }

        /// <summary>
        /// Gets or Sets TimeStampPassword
        /// </summary>
        [DataMember(Name="timeStampPassword", EmitDefaultValue=false)]
        public string TimeStampPassword { get; set; }

        /// <summary>
        /// Gets or Sets Linearize
        /// </summary>
        [DataMember(Name="linearize", EmitDefaultValue=false)]
        public bool? Linearize { get; set; }

        /// <summary>
        /// Gets or Sets DrawSignature
        /// </summary>
        [DataMember(Name="drawSignature", EmitDefaultValue=false)]
        public bool? DrawSignature { get; set; }

        /// <summary>
        /// Gets or Sets PageNumber
        /// </summary>
        [DataMember(Name="pageNumber", EmitDefaultValue=false)]
        public int? PageNumber { get; set; }

        /// <summary>
        /// Gets or Sets ShowValidationMark
        /// </summary>
        [DataMember(Name="showValidationMark", EmitDefaultValue=false)]
        public bool? ShowValidationMark { get; set; }

        /// <summary>
        /// Gets or Sets ImageData
        /// </summary>
        [DataMember(Name="imageData", EmitDefaultValue=false)]
        public byte[] ImageData { get; set; }

        /// <summary>
        /// Gets or Sets SignatureLayout
        /// </summary>
        [DataMember(Name="signatureLayout", EmitDefaultValue=false)]
        public DrawableContentLayoutParameters SignatureLayout { get; set; }

        /// <summary>
        /// Gets or Sets SignatureText
        /// </summary>
        [DataMember(Name="signatureText", EmitDefaultValue=false)]
        public PdfStandardFontAlignedTextParameters SignatureText { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PDFDigiSignParameters {\n");
            sb.Append("  CertificateData: ").Append(CertificateData).Append("\n");
            sb.Append("  CertificatePassword: ").Append(CertificatePassword).Append("\n");
            sb.Append("  FileId: ").Append(FileId).Append("\n");
            sb.Append("  SignatureMode: ").Append(SignatureMode).Append("\n");
            sb.Append("  SignatureCertificationLevel: ").Append(SignatureCertificationLevel).Append("\n");
            sb.Append("  SignatureHashAlgorithm: ").Append(SignatureHashAlgorithm).Append("\n");
            sb.Append("  SignerName: ").Append(SignerName).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  ContactInfo: ").Append(ContactInfo).Append("\n");
            sb.Append("  TimeStampURL: ").Append(TimeStampURL).Append("\n");
            sb.Append("  TimeStampUserName: ").Append(TimeStampUserName).Append("\n");
            sb.Append("  TimeStampPassword: ").Append(TimeStampPassword).Append("\n");
            sb.Append("  Linearize: ").Append(Linearize).Append("\n");
            sb.Append("  DrawSignature: ").Append(DrawSignature).Append("\n");
            sb.Append("  PageNumber: ").Append(PageNumber).Append("\n");
            sb.Append("  ShowValidationMark: ").Append(ShowValidationMark).Append("\n");
            sb.Append("  ImageData: ").Append(ImageData).Append("\n");
            sb.Append("  SignatureLayout: ").Append(SignatureLayout).Append("\n");
            sb.Append("  SignatureText: ").Append(SignatureText).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PDFDigiSignParameters);
        }

        /// <summary>
        /// Returns true if PDFDigiSignParameters instances are equal
        /// </summary>
        /// <param name="input">Instance of PDFDigiSignParameters to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PDFDigiSignParameters input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CertificateData == input.CertificateData ||
                    (this.CertificateData != null &&
                    this.CertificateData.Equals(input.CertificateData))
                ) && 
                (
                    this.CertificatePassword == input.CertificatePassword ||
                    (this.CertificatePassword != null &&
                    this.CertificatePassword.Equals(input.CertificatePassword))
                ) && 
                (
                    this.FileId == input.FileId ||
                    (this.FileId != null &&
                    this.FileId.Equals(input.FileId))
                ) && 
                (
                    this.SignatureMode == input.SignatureMode ||
                    (this.SignatureMode != null &&
                    this.SignatureMode.Equals(input.SignatureMode))
                ) && 
                (
                    this.SignatureCertificationLevel == input.SignatureCertificationLevel ||
                    (this.SignatureCertificationLevel != null &&
                    this.SignatureCertificationLevel.Equals(input.SignatureCertificationLevel))
                ) && 
                (
                    this.SignatureHashAlgorithm == input.SignatureHashAlgorithm ||
                    (this.SignatureHashAlgorithm != null &&
                    this.SignatureHashAlgorithm.Equals(input.SignatureHashAlgorithm))
                ) && 
                (
                    this.SignerName == input.SignerName ||
                    (this.SignerName != null &&
                    this.SignerName.Equals(input.SignerName))
                ) && 
                (
                    this.Reason == input.Reason ||
                    (this.Reason != null &&
                    this.Reason.Equals(input.Reason))
                ) && 
                (
                    this.Location == input.Location ||
                    (this.Location != null &&
                    this.Location.Equals(input.Location))
                ) && 
                (
                    this.ContactInfo == input.ContactInfo ||
                    (this.ContactInfo != null &&
                    this.ContactInfo.Equals(input.ContactInfo))
                ) && 
                (
                    this.TimeStampURL == input.TimeStampURL ||
                    (this.TimeStampURL != null &&
                    this.TimeStampURL.Equals(input.TimeStampURL))
                ) && 
                (
                    this.TimeStampUserName == input.TimeStampUserName ||
                    (this.TimeStampUserName != null &&
                    this.TimeStampUserName.Equals(input.TimeStampUserName))
                ) && 
                (
                    this.TimeStampPassword == input.TimeStampPassword ||
                    (this.TimeStampPassword != null &&
                    this.TimeStampPassword.Equals(input.TimeStampPassword))
                ) && 
                (
                    this.Linearize == input.Linearize ||
                    (this.Linearize != null &&
                    this.Linearize.Equals(input.Linearize))
                ) && 
                (
                    this.DrawSignature == input.DrawSignature ||
                    (this.DrawSignature != null &&
                    this.DrawSignature.Equals(input.DrawSignature))
                ) && 
                (
                    this.PageNumber == input.PageNumber ||
                    (this.PageNumber != null &&
                    this.PageNumber.Equals(input.PageNumber))
                ) && 
                (
                    this.ShowValidationMark == input.ShowValidationMark ||
                    (this.ShowValidationMark != null &&
                    this.ShowValidationMark.Equals(input.ShowValidationMark))
                ) && 
                (
                    this.ImageData == input.ImageData ||
                    (this.ImageData != null &&
                    this.ImageData.Equals(input.ImageData))
                ) && 
                (
                    this.SignatureLayout == input.SignatureLayout ||
                    (this.SignatureLayout != null &&
                    this.SignatureLayout.Equals(input.SignatureLayout))
                ) && 
                (
                    this.SignatureText == input.SignatureText ||
                    (this.SignatureText != null &&
                    this.SignatureText.Equals(input.SignatureText))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CertificateData != null)
                    hashCode = hashCode * 59 + this.CertificateData.GetHashCode();
                if (this.CertificatePassword != null)
                    hashCode = hashCode * 59 + this.CertificatePassword.GetHashCode();
                if (this.FileId != null)
                    hashCode = hashCode * 59 + this.FileId.GetHashCode();
                if (this.SignatureMode != null)
                    hashCode = hashCode * 59 + this.SignatureMode.GetHashCode();
                if (this.SignatureCertificationLevel != null)
                    hashCode = hashCode * 59 + this.SignatureCertificationLevel.GetHashCode();
                if (this.SignatureHashAlgorithm != null)
                    hashCode = hashCode * 59 + this.SignatureHashAlgorithm.GetHashCode();
                if (this.SignerName != null)
                    hashCode = hashCode * 59 + this.SignerName.GetHashCode();
                if (this.Reason != null)
                    hashCode = hashCode * 59 + this.Reason.GetHashCode();
                if (this.Location != null)
                    hashCode = hashCode * 59 + this.Location.GetHashCode();
                if (this.ContactInfo != null)
                    hashCode = hashCode * 59 + this.ContactInfo.GetHashCode();
                if (this.TimeStampURL != null)
                    hashCode = hashCode * 59 + this.TimeStampURL.GetHashCode();
                if (this.TimeStampUserName != null)
                    hashCode = hashCode * 59 + this.TimeStampUserName.GetHashCode();
                if (this.TimeStampPassword != null)
                    hashCode = hashCode * 59 + this.TimeStampPassword.GetHashCode();
                if (this.Linearize != null)
                    hashCode = hashCode * 59 + this.Linearize.GetHashCode();
                if (this.DrawSignature != null)
                    hashCode = hashCode * 59 + this.DrawSignature.GetHashCode();
                if (this.PageNumber != null)
                    hashCode = hashCode * 59 + this.PageNumber.GetHashCode();
                if (this.ShowValidationMark != null)
                    hashCode = hashCode * 59 + this.ShowValidationMark.GetHashCode();
                if (this.ImageData != null)
                    hashCode = hashCode * 59 + this.ImageData.GetHashCode();
                if (this.SignatureLayout != null)
                    hashCode = hashCode * 59 + this.SignatureLayout.GetHashCode();
                if (this.SignatureText != null)
                    hashCode = hashCode * 59 + this.SignatureText.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
