/* 
 * PassportPDF
 *
 * Copyright © 2018 ORPALIS - http://www.orpalis.com
 *
 * OpenAPI spec version: v1
 * Contact: contact@orpalis.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = PassportPDF.Client.SwaggerDateConverter;

namespace PassportPDF.Model
{
    /// <summary>
    /// Represents the parameters for a load document action request.
    /// </summary>
    [DataContract]
    public partial class PDFLoadDocumentFromByteArrayParameters :  IEquatable<PDFLoadDocumentFromByteArrayParameters>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets Conformance
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ConformanceEnum
        {
            
            /// <summary>
            /// Enum PDF for "PDF"
            /// </summary>
            [EnumMember(Value = "PDF")]
            PDF = 1,
            
            /// <summary>
            /// Enum PDFA1a for "PDF_A_1a"
            /// </summary>
            [EnumMember(Value = "PDF_A_1a")]
            PDFA1a = 2,
            
            /// <summary>
            /// Enum PDFA1b for "PDF_A_1b"
            /// </summary>
            [EnumMember(Value = "PDF_A_1b")]
            PDFA1b = 3,
            
            /// <summary>
            /// Enum PDFA2a for "PDF_A_2a"
            /// </summary>
            [EnumMember(Value = "PDF_A_2a")]
            PDFA2a = 4,
            
            /// <summary>
            /// Enum PDFA2u for "PDF_A_2u"
            /// </summary>
            [EnumMember(Value = "PDF_A_2u")]
            PDFA2u = 5,
            
            /// <summary>
            /// Enum PDFA2b for "PDF_A_2b"
            /// </summary>
            [EnumMember(Value = "PDF_A_2b")]
            PDFA2b = 6,
            
            /// <summary>
            /// Enum PDFA3a for "PDF_A_3a"
            /// </summary>
            [EnumMember(Value = "PDF_A_3a")]
            PDFA3a = 7,
            
            /// <summary>
            /// Enum PDFA3u for "PDF_A_3u"
            /// </summary>
            [EnumMember(Value = "PDF_A_3u")]
            PDFA3u = 8,
            
            /// <summary>
            /// Enum PDFA3b for "PDF_A_3b"
            /// </summary>
            [EnumMember(Value = "PDF_A_3b")]
            PDFA3b = 9,
            
            /// <summary>
            /// Enum PDF10 for "PDF1_0"
            /// </summary>
            [EnumMember(Value = "PDF1_0")]
            PDF10 = 10,
            
            /// <summary>
            /// Enum PDF11 for "PDF1_1"
            /// </summary>
            [EnumMember(Value = "PDF1_1")]
            PDF11 = 11,
            
            /// <summary>
            /// Enum PDF12 for "PDF1_2"
            /// </summary>
            [EnumMember(Value = "PDF1_2")]
            PDF12 = 12,
            
            /// <summary>
            /// Enum PDF13 for "PDF1_3"
            /// </summary>
            [EnumMember(Value = "PDF1_3")]
            PDF13 = 13,
            
            /// <summary>
            /// Enum PDF14 for "PDF1_4"
            /// </summary>
            [EnumMember(Value = "PDF1_4")]
            PDF14 = 14,
            
            /// <summary>
            /// Enum PDF15 for "PDF1_5"
            /// </summary>
            [EnumMember(Value = "PDF1_5")]
            PDF15 = 15,
            
            /// <summary>
            /// Enum PDF16 for "PDF1_6"
            /// </summary>
            [EnumMember(Value = "PDF1_6")]
            PDF16 = 16,
            
            /// <summary>
            /// Enum PDF17 for "PDF1_7"
            /// </summary>
            [EnumMember(Value = "PDF1_7")]
            PDF17 = 17,
            
            /// <summary>
            /// Enum PDF20 for "PDF2_0"
            /// </summary>
            [EnumMember(Value = "PDF2_0")]
            PDF20 = 18,
            
            /// <summary>
            /// Enum PDFUA1 for "PDF_UA_1"
            /// </summary>
            [EnumMember(Value = "PDF_UA_1")]
            PDFUA1 = 19,
            
            /// <summary>
            /// Enum Unknown for "Unknown"
            /// </summary>
            [EnumMember(Value = "Unknown")]
            Unknown = 20
        }

        /// <summary>
        /// Gets or Sets Conformance
        /// </summary>
        [DataMember(Name="conformance", EmitDefaultValue=false)]
        public ConformanceEnum? Conformance { get; set; }
        /// <summary>
        /// Gets or Sets ContentEncoding
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ContentEncodingEnum
        {
            
            /// <summary>
            /// Enum Identity for "Identity"
            /// </summary>
            [EnumMember(Value = "Identity")]
            Identity = 1,
            
            /// <summary>
            /// Enum Gzip for "Gzip"
            /// </summary>
            [EnumMember(Value = "Gzip")]
            Gzip = 2
        }

        /// <summary>
        /// Gets or Sets ContentEncoding
        /// </summary>
        [DataMember(Name="contentEncoding", EmitDefaultValue=false)]
        public ContentEncodingEnum? ContentEncoding { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PDFLoadDocumentFromByteArrayParameters" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PDFLoadDocumentFromByteArrayParameters() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PDFLoadDocumentFromByteArrayParameters" /> class.
        /// </summary>
        /// <param name="Content">Content (required).</param>
        /// <param name="FileName">FileName.</param>
        /// <param name="Password">Password.</param>
        /// <param name="Conformance">Conformance (default to ConformanceEnum.PDF).</param>
        /// <param name="ContentEncoding">ContentEncoding (default to ContentEncodingEnum.Identity).</param>
        public PDFLoadDocumentFromByteArrayParameters(byte[] Content = default(byte[]), string FileName = default(string), string Password = default(string), ConformanceEnum? Conformance = ConformanceEnum.PDF, ContentEncodingEnum? ContentEncoding = ContentEncodingEnum.Identity)
        {
            // to ensure "Content" is required (not null)
            if (Content == null)
            {
                throw new InvalidDataException("Content is a required property for PDFLoadDocumentFromByteArrayParameters and cannot be null");
            }
            else
            {
                this.Content = Content;
            }
            this.FileName = FileName;
            this.Password = Password;
            // use default value if no "Conformance" provided
            if (Conformance == null)
            {
                this.Conformance = ConformanceEnum.PDF;
            }
            else
            {
                this.Conformance = Conformance;
            }
            // use default value if no "ContentEncoding" provided
            if (ContentEncoding == null)
            {
                this.ContentEncoding = ContentEncodingEnum.Identity;
            }
            else
            {
                this.ContentEncoding = ContentEncoding;
            }
        }
        
        /// <summary>
        /// Gets or Sets Content
        /// </summary>
        [DataMember(Name="content", EmitDefaultValue=false)]
        public byte[] Content { get; set; }

        /// <summary>
        /// Gets or Sets FileName
        /// </summary>
        [DataMember(Name="fileName", EmitDefaultValue=false)]
        public string FileName { get; set; }

        /// <summary>
        /// Gets or Sets Password
        /// </summary>
        [DataMember(Name="password", EmitDefaultValue=false)]
        public string Password { get; set; }



        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PDFLoadDocumentFromByteArrayParameters {\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("  FileName: ").Append(FileName).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  Conformance: ").Append(Conformance).Append("\n");
            sb.Append("  ContentEncoding: ").Append(ContentEncoding).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PDFLoadDocumentFromByteArrayParameters);
        }

        /// <summary>
        /// Returns true if PDFLoadDocumentFromByteArrayParameters instances are equal
        /// </summary>
        /// <param name="input">Instance of PDFLoadDocumentFromByteArrayParameters to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PDFLoadDocumentFromByteArrayParameters input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Content == input.Content ||
                    (this.Content != null &&
                    this.Content.Equals(input.Content))
                ) && 
                (
                    this.FileName == input.FileName ||
                    (this.FileName != null &&
                    this.FileName.Equals(input.FileName))
                ) && 
                (
                    this.Password == input.Password ||
                    (this.Password != null &&
                    this.Password.Equals(input.Password))
                ) && 
                (
                    this.Conformance == input.Conformance ||
                    (this.Conformance != null &&
                    this.Conformance.Equals(input.Conformance))
                ) && 
                (
                    this.ContentEncoding == input.ContentEncoding ||
                    (this.ContentEncoding != null &&
                    this.ContentEncoding.Equals(input.ContentEncoding))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Content != null)
                    hashCode = hashCode * 59 + this.Content.GetHashCode();
                if (this.FileName != null)
                    hashCode = hashCode * 59 + this.FileName.GetHashCode();
                if (this.Password != null)
                    hashCode = hashCode * 59 + this.Password.GetHashCode();
                if (this.Conformance != null)
                    hashCode = hashCode * 59 + this.Conformance.GetHashCode();
                if (this.ContentEncoding != null)
                    hashCode = hashCode * 59 + this.ContentEncoding.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
